### ISSUE TITLE
Error: Invalid character 'i' in literal true

### ISSUE THREAD

**Issue by ghost** [Clijsters/PSToggl#3]
Hi @Clijsters, thanks for this great project.

In the new version (**1.2**) when start new toggle entry by `Start-TogglEntry` the script throw error:
`invalid character 'i' in literal true (expecting 'r')`.

The error is fired when `Invoke-TogglMethod` function start the `Invoke-RestMethod` function.

I notice the error is caused by last edit at [this row](https://github.com/Clijsters/PSToggl/blob/0739aa6628d72e6f0ec7684c3d12a22c741259a4/PSToggl/Private/Invoke-TogglMethod.ps1#L56).

Installing prior version (1.1) everything go right.

**Comment by clijsters** [comment]
Hi @RobDesideri,
I'm happy to hear this project is of use to someone.

This error is kind of confusing, but I will check it later. Could you please provide some output using `Start-TogglEntry` with `-Verbose` set? Which version of PowerShell are you using exactly?

I will check this commit, it changed some basic behaviour on how requests are generated, so it's basically possible that it leads to that error. Thanks for your research!

Best Regards

**Comment by clijsters** [comment]
All tests passed and [Build completed](https://ci.appveyor.com/project/Clijsters/pstoggl/build/1.2.3).
Master is still building and will be deployed to PSGallery as soon as it's complete.
You will then find the fixed version at [PSGallery - PSToggl 1.2.4](https://www.powershellgallery.com/packages/PSToggl/1.2.4).

Hope you enjoy!

**Comment by ghost** [comment]
Now all go right. Thanks @Clijsters
